---
- name: Installs Terraform and Docker on Ubuntu hosts
  hosts: ubuntu
  become: yes

  tasks:
  - name: run the four commands  
    ansible.builtin.shell: | 
      sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
      curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      sudo apt-get update && sudo apt-get install terraform

  - name: Installs Docker on Ubuntu hosts
    ansible.builtin.shell: |
      sudo apt-get remove docker docker-engine docker.io containerd runc
      sudo apt-get update && sudo apt-get install -y ca-certificates curl gnupg lsb-release
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      sudo apt-get update
      sudo apt-get install -y docker-ce docker-ce-cli containerd.io      
      sudo groupadd docker
      sudo usermod -aG docker $USER
